appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MC7/NnNrYI/62nVNB5qEv2Kj5gjlRq550Gpw1WnLuMjnwEu+jL4P9p5FT2QZ8yw4H3KFLQ9Gb6TKchcYKWAgyV1RbPCDiy21hkgU16KrVGgDBy8blMtlDWW/PSGxyYRFb+tA/D30TVGpgscj5UvU7K81tzXRgPUEEJp55WOXmpAi/nYnbuOIYZfCPY9lygQV5r9HsicqZ3Kg3uvW/CSkB5GlncyVxhK/vY8s/zymUXmG04uTNfj8mtUuDN3krrwhVawY0plOabYOGE1bxLRSgxm7YU7Kqj7dU9v64OHFeVqz3o/xHkUOfvpFgzcvqXzv/+ts61pfodxnpFivpB96Srp+SFWUn4U0ztu/SjEE1AIl2v3F5Z+5kCSvRCHPWjfBwefIhCY/sAwgLg7fTm4S7lSEJhlzHx0bvc43r/LfGKx+G/C2Iokhcrg5TdJmZeT8kSBpO0nk1eNcTCtxjdRTG37IMw3qFMt5utkClQXKmXspLxKB26X0Ambd9Upc+8PyaDGi/HQjr2YL3MHXKC4NWpl3v/9BOQFD1Bw+LN4jDMrTTcd9qIA5nX6bCfkm4vcMC8HcJZ4+d1y1E4KbUxd3QwsXi3yrwwciXqjaFVBAfW1Ut3y0lX6Twzwq22b8jUZIpETeQ5uSrqI/8pHapPTpVNqf60ulq9Zl8hrfUtYB4+0=}
